"""
Add missing DS elective courses to courses.json.
Run from the degree-optimizer root directory.
"""
import json, sys
from pathlib import Path

CATALOG = Path("backend/data/uw_madison/courses.json")

NEW_COURSES = [
    # ── Advanced Computing ──────────────────────────────────────────────────
    {
        "id": "COMP_SCI_MATH_513",
        "subject": "COMP SCI",
        "number": "513",
        "name": "Numerical Linear Algebra",
        "credits": 3,
        "cross_listed_as": ["MATH_COMP_SCI_513"],
        "prerequisites": [["MATH_340", "MATH_341", "MATH_320"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_MATH_514",
        "subject": "COMP SCI",
        "number": "514",
        "name": "Numerical Analysis",
        "credits": 3,
        "cross_listed_as": ["MATH_COMP_SCI_514"],
        "prerequisites": [["MATH_234"], ["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_557",
        "subject": "COMP SCI",
        "number": "557",
        "name": "Introduction to Computer Vision",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_BMI_576",
        "subject": "COMP SCI",
        "number": "576",
        "name": "Bioinformatics",
        "credits": 3,
        "cross_listed_as": ["BMI_COMP_SCI_576"],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEOG_573",
        "subject": "GEOG",
        "number": "573",
        "name": "GIS Foundations",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEOG_574",
        "subject": "GEOG",
        "number": "574",
        "name": "Advanced GIS",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["GEOG_573"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "MATH_444",
        "subject": "MATH",
        "number": "444",
        "name": "Introduction to Complex Variables",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_234"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_COMP_SCI_471",
        "subject": "STAT",
        "number": "471",
        "name": "Introduction to Computational Statistics",
        "credits": 3,
        "cross_listed_as": ["COMP_SCI_STAT_471"],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },

    # ── Statistical Modeling ────────────────────────────────────────────────
    {
        "id": "ACT_SCI_657",
        "subject": "ACT SCI",
        "number": "657",
        "name": "Loss Models",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall"],
        "is_upper_level": True,
    },
    {
        "id": "CIV_ENGR_516",
        "subject": "CIV ENGR",
        "number": "516",
        "name": "Introduction to Traffic Engineering",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "ECON_400",
        "subject": "ECON",
        "number": "400",
        "name": "Introduction to Econometrics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "ECON_410",
        "subject": "ECON",
        "number": "410",
        "name": "Econometrics II",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["ECON_400"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "ECON_460",
        "subject": "ECON",
        "number": "460",
        "name": "Topics in Applied Econometrics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["ECON_400"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEOG_560",
        "subject": "GEOG",
        "number": "560",
        "name": "Spatial Statistical Methods",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEOG_579",
        "subject": "GEOG",
        "number": "579",
        "name": "Remote Sensing of the Environment",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "MATH_531",
        "subject": "MATH",
        "number": "531",
        "name": "Probability Theory",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_234"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "MATH_635",
        "subject": "MATH",
        "number": "635",
        "name": "Introduction to Brownian Motion and Stochastic Calculus",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_531"]],
        "offered": ["fall"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_351",
        "subject": "STAT",
        "number": "351",
        "name": "Introduction to Probability Theory",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_222"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_421",
        "subject": "STAT",
        "number": "421",
        "name": "Applied Regression Analysis",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_ME_424",
        "subject": "STAT",
        "number": "424",
        "name": "Statistical Experimental Design",
        "credits": 3,
        "cross_listed_as": ["ME_STAT_424"],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_436",
        "subject": "STAT",
        "number": "436",
        "name": "Applied Generalized Regression",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_421"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_443",
        "subject": "STAT",
        "number": "443",
        "name": "Applied Multivariate Analysis",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_456",
        "subject": "STAT",
        "number": "456",
        "name": "Introduction to Bayesian Data Analysis",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_461",
        "subject": "STAT",
        "number": "461",
        "name": "Topics in Nonparametric Statistics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_575",
        "subject": "STAT",
        "number": "575",
        "name": "Statistical Methods for Spatial Data",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_421"]],
        "offered": ["spring"],
        "is_upper_level": True,
    },

    # ── Machine Learning ────────────────────────────────────────────────────
    {
        "id": "BSE_405",
        "subject": "BSE",
        "number": "405",
        "name": "Machine Learning for Biological Sciences",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "CHEM_361",
        "subject": "CHEM",
        "number": "361",
        "name": "Physical Chemistry: Quantum Mechanics and Spectroscopy",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["CHEM_104", "CHEM_116"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_ECE_ME_532",
        "subject": "COMP SCI",
        "number": "532",
        "name": "Matrix Methods in Machine Learning",
        "credits": 3,
        "cross_listed_as": ["ECE_COMP_SCI_ME_532", "ME_COMP_SCI_ECE_532"],
        "prerequisites": [["MATH_340", "MATH_341", "MATH_320"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_ECE_ME_539",
        "subject": "COMP SCI",
        "number": "539",
        "name": "Introduction to Artificial Neural Networks",
        "credits": 3,
        "cross_listed_as": ["ECE_COMP_SCI_ME_539", "ME_COMP_SCI_ECE_539"],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "MATH_535",
        "subject": "MATH",
        "number": "535",
        "name": "Mathematical Methods in Data Science",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_234"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "MATH_616",
        "subject": "MATH",
        "number": "616",
        "name": "Introduction to Stochastic Processes",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_531"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "PHYSICS_361",
        "subject": "PHYSICS",
        "number": "361",
        "name": "Computational Physics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["PHYSICS_202", "PHYSICS_208"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },

    # ── Other Electives ─────────────────────────────────────────────────────
    {
        "id": "ACT_SCI_655",
        "subject": "ACT SCI",
        "number": "655",
        "name": "Theory of Interest and Life Contingencies",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_ECE_533",
        "subject": "COMP SCI",
        "number": "533",
        "name": "Image Processing",
        "credits": 3,
        "cross_listed_as": ["ECE_COMP_SCI_533"],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_541",
        "subject": "COMP SCI",
        "number": "541",
        "name": "Robotics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_559",
        "subject": "COMP SCI",
        "number": "559",
        "name": "Computer Graphics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "COMP_SCI_BMI_567",
        "subject": "COMP SCI",
        "number": "567",
        "name": "Health Data Management",
        "credits": 3,
        "cross_listed_as": ["BMI_COMP_SCI_567"],
        "prerequisites": [["COMP_SCI_300", "COMP_SCI_220"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "ECE_203",
        "subject": "ECE",
        "number": "203",
        "name": "Signals, Information, and Computation",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["MATH_222"]],
        "offered": ["fall", "spring"],
        "is_upper_level": False,
    },
    {
        "id": "ECON_315",
        "subject": "ECON",
        "number": "315",
        "name": "Applied Econometrics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "ECON_570",
        "subject": "ECON",
        "number": "570",
        "name": "Economics of Organizations",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "ECON_695",
        "subject": "ECON",
        "number": "695",
        "name": "Topics in Data Science and Economics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "FW_ECOL_395",
        "subject": "F&W ECOL",
        "number": "395",
        "name": "Applied Data Analysis in Natural Resources",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "FW_ECOL_458",
        "subject": "F&W ECOL",
        "number": "458",
        "name": "Ecological Modeling",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEN_BUS_317",
        "subject": "GEN BUS",
        "number": "317",
        "name": "Business Data Analytics",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEOG_378",
        "subject": "GEOG",
        "number": "378",
        "name": "Introduction to Geographic Information Systems",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": False,
    },
    {
        "id": "GEOG_572",
        "subject": "GEOG",
        "number": "572",
        "name": "Spatial Data Science",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "GEOG_575",
        "subject": "GEOG",
        "number": "575",
        "name": "Web Cartography and Visualization",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "INFO_SYS_423",
        "subject": "INFO SYS",
        "number": "423",
        "name": "Business Intelligence",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "LIS_407",
        "subject": "LIS",
        "number": "407",
        "name": "Introduction to Data Curation",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "LIS_440",
        "subject": "LIS",
        "number": "440",
        "name": "Metadata for Information Organization",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "LIS_464",
        "subject": "LIS",
        "number": "464",
        "name": "Information Visualization",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "LIS_501",
        "subject": "LIS",
        "number": "501",
        "name": "Advanced Data Management",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "LSC_460",
        "subject": "LSC",
        "number": "460",
        "name": "Social Aspects of Information",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "LSC_660",
        "subject": "LSC",
        "number": "660",
        "name": "Data Science for Social Good",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "SOC_351",
        "subject": "SOC",
        "number": "351",
        "name": "Computational Social Science",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "SOC_CE_SOC_618",
        "subject": "SOC",
        "number": "618",
        "name": "Advanced Regression Analysis",
        "credits": 3,
        "cross_listed_as": ["CE_SOC_SOC_618"],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "SOC_CE_SOC_693",
        "subject": "SOC",
        "number": "693",
        "name": "Topics in Social Data Science",
        "credits": 3,
        "cross_listed_as": ["CE_SOC_SOC_693"],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "SOIL_SCI_585",
        "subject": "SOIL SCI",
        "number": "585",
        "name": "Environmental Data Analysis",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_405",
        "subject": "STAT",
        "number": "405",
        "name": "Mathematical Statistics I",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_311", "STAT_MATH_309"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
    {
        "id": "STAT_433",
        "subject": "STAT",
        "number": "433",
        "name": "Applied Time Series Analysis",
        "credits": 3,
        "cross_listed_as": [],
        "prerequisites": [["STAT_240"]],
        "offered": ["fall", "spring"],
        "is_upper_level": True,
    },
]

def main():
    with open(CATALOG) as f:
        data = json.load(f)

    existing_ids = {c["id"] for c in data["courses"]}
    # Also collect all cross-listed aliases
    for c in data["courses"]:
        existing_ids.update(c.get("cross_listed_as", []))

    added = []
    skipped = []
    for course in NEW_COURSES:
        if course["id"] in existing_ids:
            skipped.append(course["id"])
            continue
        data["courses"].append(course)
        added.append(course["id"])

    with open(CATALOG, "w") as f:
        json.dump(data, f, indent=2)

    print(f"Added {len(added)} courses: {', '.join(added)}")
    if skipped:
        print(f"Skipped {len(skipped)} already-present: {', '.join(skipped)}")

if __name__ == "__main__":
    main()
